# Simple workflow for deploying static content to FTP
name: Deploy static content to FTP

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment
permissions:
  contents: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "ftp-deploy"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Remove all lines between a \#GHA-REMOVE-BEGIN and \#GHA-REMOVE-END comment
        run: |
          find . -type f -name '*.sh' -exec sed -i '/#GHA-REMOVE-BEGIN/,/#GHA-REMOVE-END/d' {} +
          find . -type f -name '*.html' -exec sed -i '/#GHA-REMOVE-BEGIN/,/#GHA-REMOVE-END/d' {} +

      - name: Replace INSERT-PROJECT-NAME with actual project name
        run: |
          find . -type f -name '*.html' -exec sed -i 's/INSERT-PROJECT-NAME/LH-ZSH/g' {} +
          find . -type f -name '*.sh' -exec sed -i 's/INSERT-PROJECT-NAME/LH-ZSH/g' {} +

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_IP }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWD }}
          local-dir: ./www/
